[package]
name = "r2d2p2"
version = "0.1.0"
edition = "2021"

[dependencies]
bplustree = "0.1.0"
bson = "2.13.0"
http = "1.2.0"
chrono = "0.4.38"
sanitize-filename = "0.6.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_any = "0.5.0"